### ISSUE TITLE
ModuleNotFoundError: No module named 'global_registration'

### ISSUE THREAD

**Issue by Meijia-Zhi** [intel-isl/Open3D#1705]
anaconda3
python3.6
conda install -c open3d-admin open3d
open3d 0.9.0

>>> from global_registration import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'global_registration'
>>> x = open3d.read_point_cloud(".......some supported point cloud file")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'open3d' is not defined
>>> import open3d
>>> x = open3d.read_point_cloud(".......some supported point cloud file")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'open3d' has no attribute 'read_point_cloud'
>>> x = open3d.io.read_point_cloud(".......some supported point cloud file")
>>> print(x)
geometry::PointCloud with 0 points.
>>> 

All basic tutorial can run as expected, but when I run the program "Global registration" in Advanced , it shows: ModuleNotFoundError: No module named 'global_registration'.

**Comment by Meijia-Zhi** [comment]
I hve changed the name "global_registration.py", it can run now.
