### ISSUE TITLE
"[Open3D ERROR] [CreateFromColorAndDepth] Unsupported image format." using RGBDImages Tutorial

### ISSUE THREAD

**Issue by Me817** [intel-isl/Open3D#1942]
Hi,
I recorded some data with the Azure Kinect via Open3D and saved the frames as depth and color images along the tutorial on www.open3d.org/docs/release/tutorial/Basic/azure_kinect.html#open3d-azure-kinect-mkv-reader.

**Describe the bug**
Now I would like to convert create RGBDImages and afterwards .pcd files out of these images following the Redwood-tutorial on http://www.open3d.org/docs/release/tutorial/Basic/rgbd_image.html.

But I am receiving this error message:
```
[Open3D WARNING] Read PNG failed: unable to parse header.
Traceback (most recent call last):
  File "C:\Users\username\PycharmProjects\project\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-dc0e971ffe94>", line 1, in <module>
    runfile('C:/Users/username/PycharmProjects/project/convert_png_to_pcd.py', wdir='C:/Users/username/PycharmProjects/project')
  File "C:\Program Files\JetBrains\PyCharm 2020.1.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.1.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/username/PycharmProjects/project/convert_png_to_pcd.py", line 11, in <module>
    rgbd_img = o3d.geometry.RGBDImage.create_from_color_and_depth(color_raw, depth_raw)
RuntimeError: [Open3D ERROR] [CreateFromColorAndDepth] Unsupported image format.
```

I do not know why because the depth and the color image are both of the same size (1280x720). The depth image has bitdepth of 16 and the color image has bitdepth of 24.

**To Reproduce**
Run this code:
```
if __name__ == '__main__':
        color_raw = o3d.io.read_image("../../Desktop/bilder/color/00000.jpg")
        depth_raw = o3d.io.read_image("../../Dektop/bilder/depth/00000.png")
        rgbd_img = o3d.geometry.RGBDImage.create_from_color_and_depth(color_raw, depth_raw)
        print("rgbd-image: ", rgbd_img)
        pcd = o3d.geometry.PointCloud.create_from_rgbd_image(rgbd_img, o3d.camera.PinholeCameraIntrinsic(o3d.camera.PinholeCameraIntrinsicParameters.PrimeSenseDefault))
        pcd.transform([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]])
        o3d.visualization.draw_geometries([pcd], zoom=0.5)
```

**Environment**

- Operating system: Windows 10 64-bit
- Python version: Python 3.7.4
- Open3D version: open3d 0.10.0
- Is this remote workstation?: no
- How did you install Open3D?: pip

Any idea?

Thank you in advance.

**Comment by Me817** [comment]
I solved this supposed error. It was just a typo and the "zoom=0.5" argument in the draw_geometries was wrond even though it is wrote in the exact same way in the according tutorial (see  http://www.open3d.org/docs/release/tutorial/Basic/rgbd_image.html)
So I close this issue.
