### ISSUE TITLE
Help With Keypoint Library

### ISSUE THREAD

**Issue by nachovizzo** [intel-isl/Open3D#1944]
# Description
Hello, I'm currently working to implement some 3D Keypoints Detector/Descriptors and I need some help.

So, I'm building a skeleton before starting with the implementation, so far I have no issues with the C++ interface but with the Python one.

1. I've created a [fork](https://github.com/nachovizzo/Open3D/tree/iss_keypoints) And added a dummy Keypoint(no real stuff) and everything is working, no problems with that.

2. Given the fact I'm currently working on a dual-core machine, I can't build Open3D every time I change something, so I decided to strip what I need from the main repository.  Here is the [skeleton-project](https://github.com/nachovizzo/Open3D-Keypoints)

### C++
 The C++ interface looks to be happy and working, but I'm struggling with the python bindings
 
### Python
So, when using my `open3d_keypoints` module, I import open3d as part of it, I only want to add some small functionality but not loosing the original one, this way I can create snippets like [this one](https://github.com/nachovizzo/Open3D-Keypoints/blob/master/examples/Python/iss_detector.py)
```py
import open3d_keypoints as o3d


def main():
    bunny = o3d.io.read_triangle_mesh('../TestData/Bunny.ply')
    bunny_cloud = bunny.sample_points_uniformly(len(bunny.vertices))
    iss_keypoints = o3d.keypoints.compute_iss_keypoints(bunny_cloud)
    o3d.visualization.draw_geometries([iss_keypoints, bunny_cloud])


if __name__ == "__main__":
    main()
```
The problem is that when I use my simplified version I get this error
```py
Traceback (most recent call last):
  File "./iss_detector.py", line 17, in <module>
    main()
  File "./iss_detector.py", line 12, in main
    iss_keypoints = o3d.keypoints.compute_iss_keypoints(bunny_cloud)
TypeError: compute_iss_keypoints(): incompatible function arguments. The following argument types are supported:
    1. (input: open3d::geometry::PointCloud) -> open3d::geometry::PointCloud

Invoked with: geometry::PointCloud with 35947 points.
```

When I use the whole `Open3D` + Keypoints project, it works, and manually inspecting the pybinding I can see this huge difference.

** Open3D + Keypoints **
```py
TypeError: compute_iss_keypoints(): incompatible function arguments. The following argument types are supported:
    1. (input: open3d.open3d_pybind.geometry.PointCloud) -> open3d.open3d_pybind.geometry.PointCloud
```

** Standalone Project **
```py
TypeError: compute_iss_keypoints(): incompatible function arguments. The following argument types are supported:
    1. (input: open3d::geometry::PointCloud) -> open3d::geometry::PointCloud
````

So, I see that `open3d.open3d_pybind.geometry.PointCloud` != `open3d::geometry::PointCloud`. I do not have anything from open3d in my python bindings.

### Open questions
 - Should I re-create the whole python bindings to make it work? I mean, copy-pasting the entire `open3d_pybind` into my skeleton-project
 - On the original code, how does this symbol get defined?
 - The pybind library is not being exported, so there is no way to link against this library and extend its functionality, right?
 - What could I do to fix this?

Thanks a lot!

**Comment by nachovizzo** [comment]
This issue is now obsolete, I end up developing with the full Open3D library
