### ISSUE TITLE
Crash on CreateVisualizerWindow()

### ISSUE THREAD

**Issue by HndsmJohn** [intel-isl/Open3D#1998]
Hello, 
I recently upgraded my C++ open3D library from 0.7.0 to 0.9.0. I try to visualize geometries with the visualization methods (with a VisualizerWithKeyCallback or the DrawGeometries() function). When using the visualizer, it randomly crashes and then any other attempt at visualization ends on a runtime error, even for a simple PointCloud Visualization.
The first crash happens when using a using the Visualizer object and refreshing a PointCloud approximatly 5 times a second, if this event is linked to the crash.

**To Reproduce**
Here is the simple code i use to visualize a PointCloud. The PointCloud visualized is one of those provided in the registration examples.

```
#include <Open3D/Open3D.h>

int main (int argc, char* argv[]) {
  std::string trgt_ply = "../models/Test_models/cloud_bin_0.ply";
  auto trgt_pcl = std::make_shared<Pcl>();
  open3d::io::ReadPointCloudFromPLY(trgt_ply, *trgt_pcl);
  open3d::visualization::DrawGeometries({trgt_pcl}, "window", 1920, 1080);
  return 0;
}
```

**Expected behavior**
A visualization without the visualizer window crashing.

**Screenshots**
Here is the backtrace from gdb : 
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff5cbc801 in __GI_abort () at abort.c:79
#2  0x00007ffff6afd957 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff6b03ae6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff6b03b21 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff6b03d54 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00005555556857dc in open3d::utility::Logger::VError (this=0x555555c01fa0 <open3d::utility::Logger::i()::instance>, 
    format=<optimized out>, args=...)
    at /home/Project/ThirdParties/Open3D/src/Open3D/Utility/Console.h:90
#7  0x00005555557985c7 in open3d::utility::LogError<char const*> (format=0x5555559303ab "GLFW Error: {}")
    at /home/Project/ThirdParties/Open3D/src/Open3D/Utility/Console.h:202
#8  open3d::(anonymous namespace)::GLFWEnvironmentSingleton::GLFWErrorCallback (error=<optimized out>, 
    description=0x7fffffffb520 "Linux: Failed to watch for joystick connections in /dev/input: No space left on device")
    at /home/Project/ThirdParties/Open3D/src/Open3D/Visualization/Visualizer/Visualizer.cpp:60
#9  0x00007ffff769c9f7 in ?? () from /usr/lib/x86_64-linux-gnu/libglfw.so.3
#10 0x00007ffff76a8499 in ?? () from /usr/lib/x86_64-linux-gnu/libglfw.so.3
#11 0x00007ffff76a29d5 in ?? () from /usr/lib/x86_64-linux-gnu/libglfw.so.3
#12 0x00007ffff769cb3d in glfwInit () from /usr/lib/x86_64-linux-gnu/libglfw.so.3
#13 0x0000555555798240 in open3d::(anonymous namespace)::GLFWEnvironmentSingleton::InitGLFW ()
    at /home/Project/ThirdParties/Open3D/src/Open3D/Visualization/Visualizer/Visualizer.cpp:56
#14 open3d::visualization::Visualizer::CreateVisualizerWindow (this=this@entry=0x7fffffffd7e0, window_name="window", 
    width=width@entry=1920, height=height@entry=1080, left=left@entry=50, top=top@entry=50, visible=true)
    at /home/Project/ThirdParties/Open3D/src/Open3D/Visualization/Visualizer/Visualizer.cpp:98
#15 0x0000555555788748 in open3d::visualization::DrawGeometries (geometry_ptrs=std::vector of length 1, capacity 1 = {...}, 
    window_name="window", width=1920, height=1080, left=50, top=50)
    at /home/Project/ThirdParties/Open3D/src/Open3D/Visualization/Utility/DrawGeometry.cpp:50
#16 0x00005555556443c3 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/Project/src/DummyTests.cpp:7
```

**Environment (please complete the following information):**

- Operating system:  Ubuntu 18.04
- Open3D version: 0.9.0
- Is this remote workstation?: no
- How did you install Open3D?: built from source
- Compiler version (if built from source): gcc 7.5.0

**Additional context**
I guess the issue comes from the handling of the GLFW error (```Linux: Failed to watch for joystick connections in /dev/input: No space left on device```) in the newer versions of Open3D ? I did get this error occasionaly back when I used the 0.7.0 version but t never caused any crashes of the visualization.

Thank you in advance

**Comment by HndsmJohn** [comment]
UPDATE : I was trying to reproduce this error and I was messing around with the different open windows on my desktop and at some point, when some programs were running (Firefox, atom, ...) the error reoccurred. I guess the error is external to Open3D but it still prevents the visualization of some geometries...
