### ISSUE TITLE
1c403fdb79 Breaks python visualizer

### ISSUE THREAD

**Issue by nachovizzo** [intel-isl/Open3D#2141]
**Describe the bug**
After commit: 1c403fdb79 was introduced, I can't open the visualization tool anymore, from **python3**. I'm running Ubuntu 18.04. And after removing this commit from the master branch I can confirm that I can use the visualizer with no problems.

It segfaults right away after trying to open the visualizer `[1]    21124 segmentation fault  python3 -c ....`

**backtrace**:
```cpp
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `python3 -c import open3d as o3d;pcd = o3d.io.read_point_cloud('test.ply'); o3d.'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
>>> bt
#0  0x0000000000000000 in ?? ()
#1  0x00007fda010dd9d7 in open3d::visualization::Visualizer::InitOpenGL (this=0x7fffbf4076b0) at /home/ivizzo/dev/libs/Open3D/cpp/open3d/visualization/visualizer/VisualizerRender.cpp:51
#2  0x00007fda010ca49e in open3d::visualization::Visualizer::CreateVisualizerWindow (this=0x7fffbf4076b0, window_name=Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/../../share/gcc-10/python/libstdcxx/v6/printers.py", line 899, in to_string
    reptype = gdb.lookup_type (str (realtype) + '::_Rep').pointer ()
gdb.error: No type named class std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep.
, width=1920, height=1080, left=50, top=50, visible=true) at /home/ivizzo/dev/libs/Open3D/cpp/open3d/visualization/visualizer/Visualizer.cpp:184
#3  0x00007fda010a1692 in open3d::visualization::DrawGeometries (geometry_ptrs=std::vector of length 1, capacity 1 = {...}, window_name=Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/../../share/gcc-10/python/libstdcxx/v6/printers.py", line 899, in to_string
    reptype = gdb.lookup_type (str (realtype) + '::_Rep').pointer ()
gdb.error: No type named class std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep.
, width=1920, height=1080, left=50, top=50, point_show_normal=false, mesh_show_wireframe=false, mesh_show_back_face=false, lookat=0x0, up=0x0, front=0x0, zoom=0x0) at /home/ivizzo/dev/libs/Open3D/cpp/open3d/visualization/utility/DrawGeometry.cpp:59
#4  0x00007fda00b216d9 in open3d::<lambda(const std::vector<std::shared_ptr<const open3d::geometry::Geometry>, std::allocator<std::shared_ptr<const open3d::geometry::Geometry> > >&, const string&, int, int, int, int, bool, bool, bool)>::operator()(const std::vector<std::shared_ptr<open3d::geometry::Geometry const>, std::allocator<std::shared_ptr<open3d::geometry::Geometry const> > > &, const std::string &, int, int, int, int, bool, bool, bool) const (__closure=0x23badd8, geometry_ptrs=std::vector of length 1, capacity 1 = {...}, window_name=Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/../../share/gcc-10/python/libstdcxx/v6/printers.py", line 899, in to_string
    reptype = gdb.lookup_type (str (realtype) + '::_Rep').pointer ()
gdb.error: No type named class std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep.
, width=1920, height=1080, left=50, top=50, point_show_normal=false, mesh_show_wireframe=false, mesh_show_back_face=false) at /home/ivizzo/dev/libs/Open3D/cpp/pybind/visualization/utility.cpp:128
#5  0x00007fda00b28515 in pybind11::detail::argument_loader<std::vector<std::shared_ptr<open3d::geometry::Geometry const>, std::allocator<std::shared_ptr<open3d::geometry::Geometry const> > > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, int, bool, bool, bool>::call_impl<void, open3d::pybind_visualization_utility_methods(pybind11::module&)::<lambda(const std::vector<std::shared_ptr<const open3d::geometry::Geometry> >&, const string&, int, int, int, int, bool, bool, bool)>&, 0, 1, 2, 3, 4, 5, 6, 7, 8, pybind11::detail::void_type>(open3d::<lambda(const std::vector<std::shared_ptr<const open3d::geometry::Geometry>, std::allocator<std::shared_ptr<const open3d::geometry::Geometry> > >&, const string&, int, int, int, int, bool, bool, bool)> &, std::index_sequence, pybind11::detail::void_type &&) (this=0x7fffbf407a20, f=...) at /home/ivizzo/dev/libs/Open3D/3rdparty/pybind11/include/pybind11/cast.h:1933
#6  0x00007fda00b277fe in pybind11::detail::argument_loader<std::vector<std::shared_ptr<open3d::geometry::Geometry const>, std::allocator<std::shared_ptr<open3d::geometry::Geometry const> > > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, int, bool, bool, bool>::call<void, pybind11::detail::void_type, open3d::pybind_visualization_utility_methods(pybind11::module&)::<lambda(const std::vector<std::shared_ptr<const open3d::geometry::Geometry> >&, const string&, int, int, int, int, bool, bool, bool)>&>(open3d::<lambda(const std::vector<std::shared_ptr<const open3d::geometry::Geometry>, std::allocator<std::shared_ptr<const open3d::geometry::Geometry> > >&, const string&, int, int, int, int, bool, bool, bool)> &) (this=0x7fffbf407a20, f=...) at /home/ivizzo/dev/libs/Open3D/3rdparty/pybind11/include/pybind11/cast.h:1915
#7  0x00007fda00b25a1c in pybind11::cpp_function::<lambda(pybind11::detail::function_call&)>::operator()(pybind11::detail::function_call &) const (__closure=0x0, call=...) at /home/ivizzo/dev/libs/Open3D/3rdparty/pybind11/include/pybind11/pybind11.h:159
#8  0x00007fda00b25ab8 in pybind11::cpp_function::<lambda(pybind11::detail::function_call&)>::_FUN(pybind11::detail::function_call &) () at /home/ivizzo/dev/libs/Open3D/3rdparty/pybind11/include/pybind11/pybind11.h:137
#9  0x00007fda00590157 in pybind11::cpp_function::dispatcher (self=0x7fd9cf257480, args_in=0x7fda05761320, kwargs_in=0x0) at /home/ivizzo/dev/libs/Open3D/3rdparty/pybind11/include/pybind11/pybind11.h:624
#10 0x000000000050a7f5 in ?? ()
#11 0x000000000050c1f4 in _PyEval_EvalFrameDefault ()
#12 0x0000000000507f24 in ?? ()
#13 0x000000000063501f in PyRun_StringFlags ()
#14 0x000000000063848d in PyRun_SimpleStringFlags ()
#15 0x0000000000638fa3 in Py_Main ()
#16 0x00000000004b0dc0 in main ()
```
The *bt* points to an OpenGL call https://github.com/intel-isl/Open3D/blob/cfe5ec5bf8440a07b5506c55d384121c2dd40c77/cpp/open3d/visualization/visualizer/VisualizerRender.cpp#L51

So, my guess is that it's something that might be related to OpenGL

I can confirm that building with no `GUI` support "solves" the issue
```sh
cd build/
cmake -DENABLE_GUI=OFF ..
make install-pip-package -j16
```
Might be related to #2112

**To Reproduce**

1. Build from master
2. Run the following script in the `build/` directory
```sh
#!/usr/bin/env bash
echo "Building Open3D"
make install-pip-package -j16

echo "Checking Installation"
python3 -c "import open3d as o3d;pcd = o3d.io.read_point_cloud('test.ply'); o3d.visualization.draw_geometries([pcd])"
```

**Expected behavior**
The visualizer opens

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04
- Python version: Python 3.6.9
- Open3D version: master branch
- Is this remote workstation?: no
- How did you install Open3D?:  build from source
- Compiler version: gcc 7.5

**Additional context**

I merged the master branch onto #1966 and was expecting this issue to go away, but since some weeks this is not happening and I'm blocked on finishing that PR :)

**Comment by nachovizzo** [comment]
So, this is not happening anymore on my local installation. I have literally no idea what/which thing fixed it, but I'll close it anyways
