### ISSUE TITLE
pip install fails in OSX Catalina 10.15.5 due to lack of version control on dependency (notebook)

### ISSUE THREAD

**Issue by agporto** [intel-isl/Open3D#2142]
When pip installing open3d 0.9.0 and 0.10.0 on OSX Catalina 10.15.5, installation fails with the following error message:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -pthread -Wall -g -fPIC -msse2 -Iextras/libargon2/src/../include -Iextras/libargon2/src/blake2 -c extras/libargon2/src/argon2.c -o build/temp.macosx-10.13-x86_64-3.6/extras/libargon2/src/argon2.o
  extras/libargon2/src/argon2.c:18:10: fatal error: 'string.h' file not found
  #include <string.h>
           ^~~~~~~~~~
  1 error generated.
  error: command '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for argon2-cffi
Failed to build argon2-cffi
ERROR: Could not build wheels for argon2-cffi which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 20.1.1; however, version 20.2.1 is available.
You should consider upgrading via the '/Applications/Slicer.app/Contents/bin/./python-real -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Applications/Slicer.app/Contents/bin/Python/slicer/util.py", line 2444, in pip_install
    _executePythonModule('pip', args)
  File "/Applications/Slicer.app/Contents/bin/Python/slicer/util.py", line 2420, in _executePythonModule
    logProcessOutput(proc)
  File "/Applications/Slicer.app/Contents/bin/Python/slicer/util.py", line 2392, in logProcessOutput
    raise CalledProcessError(retcode, proc.args, output=proc.stdout, stderr=proc.stderr)
subprocess.CalledProcessError: Command '['/Applications/Slicer.app/Contents/bin/../bin/PythonSlicer', '-m', 'pip', 'install', 'open3d==0.9.0']' returned non-zero exit status 1.
```
The error seems to be a consequence of lack of version control of the dependency `notebook`, which added on July 31st the following dependency `argon2-cffi` , which doesn’t have a OSX wheel available.

**Comment by yxlao** [comment]
Seems like this is related to `argon2-cffi` but not Open3D.

Try to see if 
```
pip install argon2-cffi
```
works.

Closing for now. Feel free to comment.

**Comment by agporto** [comment]
I was able to install things after debugging (I simply used a previous version of the notebook library). But I thought to report to open3d given that open3d does not currently have version control on the required python libraries. Anyone installing open3d using pip in MacOS Catalina 10.15.5. will have to go through the same process as me.

**Comment by agporto** [comment]
Closing for now, but I still think it is something open3d should consider

**Comment by yxlao** [comment]
good point, thanks
