### ISSUE TITLE
Issue with TSDFVoxelGrid on CUDA and PyTorch 

### ISSUE THREAD

**Issue by vfdev-5** [intel-isl/Open3D#3294]
**IMPORTANT: Please use the following template to report the bug.**
_____

**Describe the bug**

CUDA context seems to be broken if using pytorch cuda tensors and TSDFVoxelGrid (or specifically Hashmap).

**To Reproduce**

With master version: `0.12.0+317628457`

```python
import torch


def main():

    print("---")
    d = torch.tensor([0.0, 0.5, 0.7, 1.0], device="cuda")
    print(d.mean())
    print("---")

    import numpy as np
    import open3d as o3d
    import open3d.core as o3c

    print("o3d: ", o3d.__version__)

    # voxel_size = 3.0 / 512.0  # voxel resolution in meters
    # sdf_trunc = 0.04  # truncation distance in meters
    # block_resolution = 16  # 16^3 voxel blocks
    # initial_block_count = 100  # initially allocated number of voxel blocks
    # device = o3d.core.Device('CUDA:0')

    # volume = o3d.t.geometry.TSDFVoxelGrid(
    #     {
    #         'tsdf': o3d.core.Dtype.Float32,
    #         'weight': o3d.core.Dtype.UInt16,
    #         'color': o3d.core.Dtype.UInt16
    #     },
    #     voxel_size=voxel_size,
    #     sdf_trunc=sdf_trunc,
    #     block_resolution=block_resolution,
    #     block_count=initial_block_count,
    #     device=device
    # )

    print("---")

    hm = o3c.Hashmap(100, o3c.Dtype.Int32, o3c.Dtype.UInt8, device=o3c.Device("CUDA:0"))

    d = torch.tensor([0.0, 0.5, 0.7, 1.0], device="cuda")
    print(d.mean())

    print("---")

    return 0


if __name__ == "__main__":
    main()

```
>
```
---
tensor(0.5500, device='cuda:0')
---
o3d:  0.12.0+317628457
---
tensor(0.5500, device='cuda:0')
---
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  after reduction step 1: cudaErrorInvalidDevice: invalid device ordinal
Aborted (core dumped)
```

In this case CUDA context is firstly created by pytorch tensor. If we first create the Hashmap and remove the first `d = torch.tensor([0.0, 0.5, 0.7, 1.0], device="cuda")` then it gives bad allocation (due to invalid size):
```
---
---
o3d:  0.12.0+317628457
---
Traceback (most recent call last):
  File "repro_tfsd_voxel_grid.py", line 61, in <module>
    main()
  File "repro_tfsd_voxel_grid.py", line 53, in main
    print(d.mean())
  File "/opt/conda/lib/python3.8/site-packages/torch/tensor.py", line 193, in __repr__
    return torch._tensor_str._str(self)
  File "/opt/conda/lib/python3.8/site-packages/torch/_tensor_str.py", line 383, in _str
    return _str_intern(self)
  File "/opt/conda/lib/python3.8/site-packages/torch/_tensor_str.py", line 358, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/opt/conda/lib/python3.8/site-packages/torch/_tensor_str.py", line 242, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/opt/conda/lib/python3.8/site-packages/torch/_tensor_str.py", line 90, in __init__
    nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
RuntimeError: CUDA out of memory. Tried to allocate 3.94 GiB (GPU 0; 10.92 GiB total capacity; 7.88 GiB already allocated; 2.35 GiB free; 7.88 GiB reserved in total by PyTorch)
```

**Expected behavior**

We should not have any errors

**Environment (please complete the following information):**

- Operating system: Ubuntu 18.04
- Python version: Python 3.8.8
- Open3D version: 0.12.0+317628457
- Is this remote workstation?: yes
- How did you install Open3D?: build from source
- Compiler version (if built from source): gcc 7.5.0, 
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
```

**Additional context**

pytorch version:  1.8.1           py3.8_cuda11.1_cudnn8.0.5_0 

from docker image : pytorch/pytorch:1.8.1-cuda11.1-cudnn8-devel

**Comment by vfdev-5** [comment]
There is no issues between Open3D and pytorch nightly (https://github.com/pytorch/pytorch/issues/54415#issuecomment-820805883), so maybe we can close this issue...

**Comment by sanskar107** [comment]
@vfdev-5 right, there is a known issue in Pytorch 1.8 and CUDA 11.* It should be fixed in a future pytorch release.
