### ISSUE TITLE
ModuleNotFoundError: No module named 'open3d.cpu' on importing open3D with CUDA 11.0

### ISSUE THREAD

**Issue by VisionaryMind** [intel-isl/Open3D#3508]
**Describe the bug**
Compiling Open3D, either version 0.12.0 / 0.11.0 with CUDA 11.3 / 11.0, completes without error. I am also able to create a Python / pip package and install. Upon trying to import, it is clear there are no modules available, including the first that is called "cpu":

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/anaconda3/lib/python3.8/site-packages/open3d/__init__.py", line 83, in <module>
    from open3d.cpu.pybind import (camera, geometry, io, pipelines, utility, t)
ModuleNotFoundError: No module named 'open3d.cpu'
```

**To Reproduce**

(base) user@computer:~/Downloads/Open3D/build$ **python**
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
`>>>` **import open3d**

**Environment (please complete the following information):**

- Operating system: Ubuntu 20.04
- Python version: Python 3.8.4 (Anaconda)
- Open3D version: 0.11.0
- Is this remote workstation?: no
- How did you install Open3D?: build from source
- Compiler version (if built from source): GCC 9.3.0

**Additional context**

I am well aware that this issue has been raised multiple times in the past, but none of the recommended solutions have worked. There is no indication, for example, that symbol loading is failing on import. On the contrary, it looks like there is a comiplete lack of module access, such that even `__DEVICE_API__ ` cannot be found and, therefore, the API cannot be correctly set to CUDA.

In fact, if I disable all CPU API code in `__init__.py`, all the GPU code fails, because the modules cannot be found. I am clearly missing something here and need help to get this working -- as even running `pip install open3d-python` leads to the same problem. 

Just to confirm, open3D has been installed with `sudo checkinstall`, binaries are available. The python / pip packages build without errors. 

Here is the CMake output:

```
CMAKE_BUILD_TYPE is set to Release.
OPEN3D_THIRD_PARTY_DOWNLOAD_DIR is not specified, will download directly.

Open3D 0.12.0+ff11ad20d
Using python from PYTHON_EXECUTABLE variable: /home/user/anaconda3/bin/python
(PYTHON_EXECUTABLE matches python from PATH)
Using security hardening compiler flags: -fstack-protector-strong;-Wformat;-Wformat-security and
linker flags: -Wl,-z,noexecstack;-Wl,-z,relro,-z,now;-pie
Building with user-provided architectures
CMAKE_CUDA_ARCHITECTURES: 75
Building library Assimp from source
Building with OpenMP
Building library 3rdparty_eigen3 from source
Building library 3rdparty_flann from source
Building library 3rdparty_nanoflann from source
Building library 3rdparty_glew from source
Building library 3rdparty_glfw3 from source
Using X11 for window creation
Building third-party library JPEG from source
NASM assembler not found - libjpeg-turbo performance may suffer
libturbojpeg: WITH_CRT_DLL=ON
Building library 3rdparty_lzf from source
Building library 3rdparty_tritriintersect from source
Set USE_SYSTEM_LIBREALSENSE=OFF, because GLIBCXX_USE_CXX11_ABI is OFF.
Building library 3rdparty_rply from source
Building library 3rdparty_tinyfiledialogs from source
Building library 3rdparty_tinygltf from source
Building library 3rdparty_tinyobjloader from source
Building library 3rdparty_qhull_r from source
Building library 3rdparty_qhullcpp from source
Building library 3rdparty_fmt from source
Building tests with Eigen v3.3.90
Found Boost 1.70.0 at /home/user/anaconda3/lib/cmake/Boost-1.70.0
  Requested configuration: QUIET
Found boost_headers 1.70.0 at /home/user/anaconda3/lib/cmake/boost_headers-1.70.0
Catch not detected. Interpreter tests will be skipped. Install Catch headers manually or use `cmake -DDOWNLOAD_CATCH=1` to fetch them automatically.
pybind11 v2.5.0
Building library 3rdparty_poisson from source
Building library 3rdparty_imgui from source
Using prebuilt third-party library Filament
GLIBC version 2.31-0 found: Downloading Open3D Filament binary.
Filament is located at /home/user/Downloads/Open3D/build/filament/src/ext_filament
CLANG_LIBDIR: /usr/lib/x86_64-linux-gnu
CPP_LIBRARY: /usr/lib/x86_64-linux-gnu/libc++.so
CPPABI_LIBRARY: /usr/lib/x86_64-linux-gnu/libc++abi.so
Building library 3rdparty_parallelstl from source
Using remote url(s): https://github.com/intel-isl/Open3D/releases/download/v0.12.0/mkl-include-2020.1-intel_217-linux-64.tar.bz2;https://anaconda.org/intel/mkl-include/2020.1/download/linux-64/mkl-include-2020.1-intel_217.tar.bz2
Using remote url(s): https://github.com/intel-isl/Open3D/releases/download/v0.12.0/mkl-static-2020.1-intel_217-linux-64.tar.bz2;https://anaconda.org/intel/mkl-static/2020.1/download/linux-64/mkl-static-2020.1-intel_217.tar.bz2
Using remote url(s): https://github.com/intel-isl/Open3D/releases/download/v0.10.0/linux-merged-mkl-static-2020.1-intel_217.zip
Using MKL to support BLAS and LAPACK functionalities.
STATIC_MKL_INCLUDE_DIR: /home/user/Downloads/Open3D/build/mkl_install/include/
STATIC_MKL_LIB_DIR: /home/user/Downloads/Open3D/build/mkl_install/lib
STATIC_MKL_LIBRARIES: mkl_merged;tbb_static
Building third-party library faiss from source
FAISS_INCLUDE_DIR: /home/user/Downloads/Open3D/build/mkl_install/include/
FAISS_LIB_DIR: /home/user/Downloads/Open3D/build/mkl_install/lib
Using remote url(s): https://raw.githubusercontent.com/opencv/opencv_3rdparty/a56b6ac6f030c312b2dce17430eef13aed9af274/ippicv/ippicv_2020_lnx_intel64_20191018_general.tgz
IPP-ICV 2020.0.0 Gold available. Building interface wrappers IPP-IW.
Building TensorFlow ops
Building TensorFlow ops with CUDA
Using python from PYTHON_EXECUTABLE variable: /home/user/anaconda3/bin/python
(PYTHON_EXECUTABLE matches python from PATH)
Getting TensorFlow properties ...
2021-05-27 13:25:34.859658: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0

2021-05-27 13:25:35.783448: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0

2021-05-27 13:25:36.700255: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0

2021-05-27 13:25:37.615342: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0

2021-05-27 13:25:38.537398: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0

TensorFlow       version: 2.5.0
             include dir: /home/user/anaconda3/lib/python3.8/site-packages/tensorflow/include
             library dir: /home/user/anaconda3/lib/python3.8/site-packages/tensorflow
           framework lib: /home/user/anaconda3/lib/python3.8/site-packages/tensorflow/libtensorflow_framework.so.2
             definitions: _GLIBCXX_USE_CXX11_ABI=0
           use cxx11 abi: 0
TensorFlow matches Open3D ABI: 0 == OFF
Copying /home/user/Downloads/Open3D/cpp/open3d/visualization/webrtc_server/html to /home/user/Downloads/Open3D/build/bin/resources.
npm found at: /usr/bin/npm. Jupyter support will be enabled.
BUILD_JUPYTER_EXTENSION is set to ON
Using Python version: 3.8
Using Python version major: 3
PYPI_PACKAGE_NAME: open3d
Using python from PYTHON_EXECUTABLE variable: /home/user/anaconda3/bin/python
(PYTHON_EXECUTABLE matches python from PATH)
Getting TensorFlow properties ...
2021-05-27 13:25:39.498431: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0

2021-05-27 13:25:40.415969: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0

2021-05-27 13:25:41.329289: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0

2021-05-27 13:25:42.251266: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0

2021-05-27 13:25:43.163516: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0

TensorFlow       version: 2.5.0
             include dir: /home/user/anaconda3/lib/python3.8/site-packages/tensorflow/include
             library dir: /home/user/anaconda3/lib/python3.8/site-packages/tensorflow
           framework lib: /home/user/anaconda3/lib/python3.8/site-packages/tensorflow/libtensorflow_framework.so.2
             definitions: _GLIBCXX_USE_CXX11_ABI=0
           use cxx11 abi: 0
TensorFlow matches Open3D ABI: 0 == OFF
================================================================================
Open3D 0.12.0 Configuration Summary
================================================================================
Enabled Features:
  OpenMP .................................. ON
  Headless Rendering ...................... OFF
  Azure Kinect Support .................... ON
  Intel RealSense Support ................. ON
  CUDA Support ............................ ON
  Build GUI ............................... ON
  Build WebRTC visualizer ................. ON
  Build Shared Library .................... ON
  Build Unit Tests ........................ OFF
  Build Examples .......................... ON
  Build Python Module ..................... ON
  Build Jupyter Extension ................. ON
  Build TensorFlow Ops .................... ON
  Build PyTorch Ops ....................... OFF
  Build Benchmarks ........................ OFF
  Bundle Open3D-ML ........................ ON
  Build RPC interface ..................... OFF
  Force GLIBCXX_USE_CXX11_ABI= ............ 0
================================================================================
Third-Party Dependencies:
  EIGEN3 .................................. yes (build from source)
  FAISS ................................... yes (build from source)
  FILAMENT ................................ yes (build from source)
  FLANN ................................... yes (build from source)
  FMT ..................................... yes (build from source)
  GLEW .................................... yes (build from source)
  GLFW .................................... yes (build from source)
  GOOGLETEST .............................. no
  IMGUI ................................... yes (build from source)
  IPPICV .................................. yes (build from source)
  JPEG .................................... yes (build from source)
  JSONCPP ................................. yes (build from source)
  LIBLZF .................................. yes (build from source)
  OPENGL .................................. yes (build from source)
  PNG ..................................... yes (build from source)
  PYBIND11 ................................ yes (build from source)
  QHULL ................................... yes (build from source)
  LIBREALSENSE ............................ yes (build from source)
  TINYFILEDIALOGS ......................... yes (build from source)
  TINYGLTF ................................ yes (build from source)
  TINYOBJLOADER ........................... yes (build from source)
  WEBRTC .................................. yes (build from source)
================================================================================
Configuring done
```

**Comment by VisionaryMind** [comment]
I was able to get this working by uninstalling PyBind11 2.6.2 and re-installing the system's PyBind (2.4.3), however, now that importing open3d works, there are no CUDA modules available -- it defaults to CPU. Further, the CPU version does not seem to be able to handle point cloud sizes typical for our project (10 million + points) -- it throws a Segmentation fault (core dumped). This is obviously another issue, so I will open in a separate thread.

For now, this issue is partially resolved. `open3d.cpu` can be imported, but cuda modules are not.

**Comment by VisionaryMind** [comment]
It turns out this problem was happening because O3D couldn't enumerate the GPU list. The NVIDIA CUDA graphics drivers needed to be completely removed and then re-installed. NVIDIA-SMI confirmed that the GPU could be identified by the system, and then O3D could correctly switch the device API to CUDA.
