### ISSUE TITLE
numpy.linalg.LinAlgError: Singular matrix  when running reconstruction_system/run_system.py --make

### ISSUE THREAD

**Issue by ekolve** [intel-isl/Open3D#3791]
I receive the following exception when running:

```bash
python  run_system.py config/realsense.json --make
```

```bash
Traceback (most recent call last):
  File "run_system.py", line 91, in <module>
    make_fragments.run(config)
  File "/Users/erick/github/Open3D/examples/python/reconstruction_system/make_fragments.py", line 185, in run
    Parallel(n_jobs=MAX_THREAD)(delayed(process_single_fragment)(
  File "/Users/erick/venv-open3d/lib/python3.8/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/Users/erick/venv-open3d/lib/python3.8/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/erick/venv-open3d/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
numpy.linalg.LinAlgError: Singular matrix
```

I created a rosbag dataset using a RealSense L515 camera with the script `sensors/realsense_recorder.py`.  The rosbag file is ~3.2G, which I can share through S3 if that would help in identifying the issue.  I don't get this error with every rosbag file that I create, but there isn't a clear reason why recording some datasets result in this error during `--make` and others do not.  I am using the latest master (sha: 7c62640441e3da18bcbe146723ed83ff544b2fbb).

**Comment by ekolve** [comment]
Closing issue - can't reproduce with just the .bag file.

**Comment by Conan-lza** [comment]
> Closing issue - can't reproduce with just the .bag file.
I got the same bug when running with my own dataset, which is a folder with image and depth inside. Sometimes I could get final result successfully, but sometimes it came out with the error the same as yours.
I can't figure it out, could you please give me some advice?
