### ISSUE TITLE
Installing open3d python package from source on Windows produces error

### ISSUE THREAD

**Issue by Codinggreg** [intel-isl/Open3D#905]
**Describe the bug**

``` 
 Traceback (most recent call last):
    File "setup.py", line 108, in <module>
      zip_safe=False,
    File "C:\Vyoo\sources\Open3D\env\lib\site-packages\setuptools\__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "C:\Program Files\Python36\lib\distutils\core.py", line 134, in setup
      ok = dist.parse_command_line()
    File "C:\Vyoo\sources\Open3D\env\lib\site-packages\setuptools\dist.py", line 499, in parse_command_line
      result = _Distribution.parse_command_line(self)
    File "C:\Program Files\Python36\lib\distutils\dist.py", line 472, in parse_command_line
      args = self._parse_command_opts(parser, args)
    File "C:\Vyoo\sources\Open3D\env\lib\site-packages\setuptools\dist.py", line 814, in _parse_command_opts
      nargs = _Distribution._parse_command_opts(self, parser, args)
    File "C:\Program Files\Python36\lib\distutils\dist.py", line 534, in _parse_command_opts
      if not issubclass(cmd_class, Command):
  TypeError: issubclass() arg 1 must be a class
```
**To Reproduce**
Following the installation tutorial [ĥere](http://www.open3d.org/docs/compilation.html#windows)
1. (using py launcher) `py -3.6 -m venv env`
2. `.\env\scripts\activate`
3. `mkdir build`
4. `cd build`
5. `cmake -G "VisualStudio 16 2019" ..`
6. `cmake --build . --parallel 4 --config Release --target ALL_BUILD`
7. `cmake --build . --parallel 4 --config Release --target install-pip-package`
8. see error

**Expected behavior**
I should be able to do python -c "import open3d" successfully after running step 7

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.6.7
 - Open3D version: as of commit eea7fd2
 - Is this remote workstation?: no
 - How did you install Open3D?: Compiling from source and installing package with pip

Additionnal stuff:
- Using Visual Studio 16 2019
- CMake version 3.14.1
- Python 3.6.7
- Pip 19.0.3

**Additional context**
I am compiling from source to disable OpenMP as described in #797 and #831 

Full log
```
Microsoft (R) Build Engine version 16.0.461+g6ff56ef63c for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  glfw.vcxproj -> C:\Vyoo\sources\Open3D\build\lib\Release\glfw3.lib
  Integration.vcxproj -> C:\Vyoo\sources\Open3D\build\src\Open3D\Integration\Integration.dir\Release\Integration.lib
  jpeg.vcxproj -> C:\Vyoo\sources\Open3D\build\lib\Release\jpeg.lib
  Camera.vcxproj -> C:\Vyoo\sources\Open3D\build\src\Open3D\Camera\Camera.dir\Release\Camera.lib
  IO.vcxproj -> C:\Vyoo\sources\Open3D\build\src\Open3D\IO\IO.dir\Release\IO.lib
  ColorMap.vcxproj -> C:\Vyoo\sources\Open3D\build\src\Open3D\ColorMap\ColorMap.dir\Release\ColorMap.lib
  Odometry.vcxproj -> C:\Vyoo\sources\Open3D\build\src\Open3D\Odometry\Odometry.dir\Release\Odometry.lib
  glew.vcxproj -> C:\Vyoo\sources\Open3D\build\lib\Release\glew.lib
  Geometry.vcxproj -> C:\Vyoo\sources\Open3D\build\src\Open3D\Geometry\Geometry.dir\Release\Geometry.lib
  Utility.vcxproj -> C:\Vyoo\sources\Open3D\build\src\Open3D\Utility\Utility.dir\Release\Utility.lib
  Registration.vcxproj -> C:\Vyoo\sources\Open3D\build\src\Open3D\Registration\Registration.dir\Release\Registration.li
  b
  EncodeShader.vcxproj -> C:\Vyoo\sources\Open3D\build\bin\Release\EncodeShader.exe
  jsoncpp.vcxproj -> C:\Vyoo\sources\Open3D\build\lib\Release\jsoncpp.lib
  tinyfiledialogs.vcxproj -> C:\Vyoo\sources\Open3D\build\lib\Release\tinyfiledialogs.lib
  zlib.vcxproj -> C:\Vyoo\sources\Open3D\build\lib\Release\zlib.lib
  png.vcxproj -> C:\Vyoo\sources\Open3D\build\lib\Release\png.lib
  Visualization.vcxproj -> C:\Vyoo\sources\Open3D\build\src\Open3D\Visualization\Visualization.dir\Release\Visualizatio
  n.lib
  Open3D.vcxproj -> C:\Vyoo\sources\Open3D\build\lib\Release\Open3D.lib
  open3d.vcxproj -> C:\Vyoo\sources\Open3D\build\lib\Python\Release\open3d.cp36-win_amd64.pyd
  -- Jupyter support is enabled. Building Jupyter plugin ...

  > open3d@0.6.0 prepare C:\Vyoo\sources\Open3D\build\lib\python_package\js
  > webpack

  Hash: cf0635841172b472ed57cf089d3b292cc282df31
  Version: webpack 4.29.6
  Child
      Hash: cf0635841172b472ed57
      Time: 161ms
      Built at: 2019-04-11 14:17:17
             Asset      Size  Chunks             Chunk Names
      extension.js  1.07 KiB       0  [emitted]  main
      Entrypoint main = extension.js
      [0] ./extension.js 660 bytes {0} [built]

      WARNING in configuration
      The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'd
  evelopment' or 'production' to enable defaults for each environment.
      You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/
  Child
      Hash: cf089d3b292cc282df31
      Time: 2395ms
      Built at: 2019-04-11 14:17:19
                                     Asset       Size  Chunks                    Chunk Names
      12c8482249da928cedbafe8c3d624c0b.png  494 bytes          [emitted]
                                  index.js    640 KiB       0  [emitted]  [big]  main
                              index.js.map   2.47 MiB       0  [emitted]         main
      Entrypoint main [big] = index.js index.js.map
      [0] ./assets/disc.png 82 bytes {0} [built]
      [1] ./index.js 728 bytes {0} [built]
      [2] ./j_visualizer.js 6.78 KiB {0} [built]
      [3] external "@jupyter-widgets/base" 42 bytes {0} [built]
      [5] (webpack)/buildin/global.js 472 bytes {0} [built]
      [6] (webpack)/buildin/module.js 497 bytes {0} [built]
      [9] ./package.json 1.31 KiB {0} [built]
          + 3 hidden modules

      WARNING in configuration
      The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'd
  evelopment' or 'production' to enable defaults for each environment.
      You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

      WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
      This can impact web performance.
      Assets:
        index.js (640 KiB)

      WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (
  244 KiB). This can impact web performance.
      Entrypoints:
        main (640 KiB)
            index.js


      WARNING in webpack performance recommendations:
      You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your applic
  ation.
      For more info visit https://webpack.js.org/guides/code-splitting/
  npm notice created a lockfile as package-lock.json. You should commit this file.
  npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies y
  ourself.
  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
  npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"
  any"} (current: {"os":"win32","arch":"x64"})

  audited 5564 packages in 11.601s
  found 0 vulnerabilities

  Traceback (most recent call last):
    File "setup.py", line 108, in <module>
      zip_safe=False,
    File "C:\Vyoo\sources\Open3D\env\lib\site-packages\setuptools\__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "C:\Program Files\Python36\lib\distutils\core.py", line 134, in setup
      ok = dist.parse_command_line()
    File "C:\Vyoo\sources\Open3D\env\lib\site-packages\setuptools\dist.py", line 499, in parse_command_line
      result = _Distribution.parse_command_line(self)
    File "C:\Program Files\Python36\lib\distutils\dist.py", line 472, in parse_command_line
      args = self._parse_command_opts(parser, args)
    File "C:\Vyoo\sources\Open3D\env\lib\site-packages\setuptools\dist.py", line 814, in _parse_command_opts
      nargs = _Distribution._parse_command_opts(self, parser, args)
    File "C:\Program Files\Python36\lib\distutils\dist.py", line 534, in _parse_command_opts
      if not issubclass(cmd_class, Command):
  TypeError: issubclass() arg 1 must be a class
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(209
,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Vyoo\sources\Open3D\build\src\Python\pip-package.vcxproj]
```

**Comment by qianyizh** [comment]
@yxlao take a look?
