### ISSUE TITLE
Problem compiling open3d v.0.6.0 using python 3.7 in ubuntu 16.04

### ISSUE THREAD

**Issue by dhorka** [intel-isl/Open3D#970]
**Describe the bug**
It can not be compiled open3d v.0.6.0 using python 3.7  in ubuntu 16.04

**To Reproduce**
1. git clone --recursive https://github.com/intel-isl/Open3D
2. git checkout tags/v0.6.0 -b 0.6.0
3. git submodule sync 
4. git submodule update --init --recursive
5. mkdir build
6. cd build
7. cmake  ..
8. make -j$(nproc)
9. make install-pip-package

**Screenshots**
```
[100%] Built target python-package
Traceback (most recent call last):
  File "setup.py", line 108, in <module>
    zip_safe=False,
  File "/home/dhorka/usr-ubuntu-16.04/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/dhorka/usr-ubuntu-16.04/lib/python3.7/distutils/core.py", line 134, in setup
    ok = dist.parse_command_line()
  File "/home/dhorka/usr-ubuntu-16.04/lib/python3.7/site-packages/setuptools/dist.py", line 710, in parse_command_line
    result = _Distribution.parse_command_line(self)
  File "/home/dhorka/usr-ubuntu-16.04/lib/python3.7/distutils/dist.py", line 483, in parse_command_line
    args = self._parse_command_opts(parser, args)
  File "/home/dhorka/usr-ubuntu-16.04/lib/python3.7/site-packages/setuptools/dist.py", line 1025, in _parse_command_opts
    nargs = _Distribution._parse_command_opts(self, parser, args)
  File "/home/dhorka/usr-ubuntu-16.04/lib/python3.7/distutils/dist.py", line 545, in _parse_command_opts
    if not issubclass(cmd_class, Command):
TypeError: issubclass() arg 1 must be a class
src/Python/CMakeFiles/pip-package.dir/build.make:57: recipe for target 'src/Python/CMakeFiles/pip-package' failed
make[3]: *** [src/Python/CMakeFiles/pip-package] Error 1
CMakeFiles/Makefile2:1272: recipe for target 'src/Python/CMakeFiles/pip-package.dir/all' failed
make[2]: *** [src/Python/CMakeFiles/pip-package.dir/all] Error 2
CMakeFiles/Makefile2:1209: recipe for target 'src/Python/CMakeFiles/install-pip-package.dir/rule' failed
make[1]: *** [src/Python/CMakeFiles/install-pip-package.dir/rule] Error 2
Makefile:435: recipe for target 'install-pip-package' failed
make: *** [install-pip-package] Error 2
```

**Environment (please complete the following information):**
 - OS: Ubuntu 16
 - Python version: 3.7
 - Open3D version: 0.6.0
 - Is this remote workstation?: no
 - How did you install Open3D?: build_from_source 

**Additional context**
The python 3.7  was compiled from source and used to compile pytorch from source.

**Comment by tpwrules** [comment]
I am having this same issue on Ubuntu 18.04 and the Python 3.7.3 from the deadsnakes PPA.

**Comment by yxlao** [comment]
From the error message, it seems that from `wheel.bdist_wheel import bdist_wheel` failed, and thus `bdist_wheel` is `None`. Added a fix to handle print warning and handles this case in #1012 .
